### ISSUE TITLE
DAMAGE BUG FOR ALL ARMOR MINECRAFT

### ISSUE THREAD

**Issue by TaiKInGithub** [Heisenburger69/BurgerCustomArmor#20] opened 2020-07-25 10:25 UTC
A diamond armor enchanting protection 4 this makes kill in any blow with an iron sword more I removed the plugins then no more bug of damage 
THANK YOU FOR SETTLING THIS AS SOON AS POSSIBLE.

**Comment by Heisenburger69** [comment] 2020-09-24 18:47
Duplicate of #16

**Closed by Heisenburger69** 2020-09-24 18:47 UTC
